### ISSUE TITLE
Feedback - Give more hints on how to build the manifest file in real life with real data

### ISSUE THREAD

**Issue by toirl** [Green-Software-Foundation/if-docs#75]
Hi all :)

## Scope

What does your feedback relate to?

- [x] Documentation

## Details

I just start working with the impact framework. I read the documentation and watched the video from the cabon hack. I think I pretty much understand the central role of the manifest file as the source and model for all computations. I saw the plugin to generate fake data to get startet.

However I was/are struggling on the question how to create this manifest file with real data. How to I get data from my machines? 

## Expected Behaviour

I would expect some clear(er) hints on how the Manifest files can be generated. Maybe there are multiple ways. Either using Input plugins are manually crafting the static manifest files for further computation. 

## Actual behaviour

I found very little information on that. The FAQ (https://if.greensoftware.foundation/FAQ#is-there-any-way-to-auto-generate-manifest-files) refers to that, but that didn't help me so much in the first place. After I spent more time on figuring out how it could work?

## Proposed actions

I propose to add a section like "How to get data in manifest file" under https://if.greensoftware.foundation/users/how-to-write-manifests. I can offer my help and write a PR for this which might be also a good prove of my own understanding.

**Comment by jmcook1186** [comment]
Hi @toirl 

thanks for opening the issue. Grabbing data from real machines can certainly be challenging. One of the reasons it's not comprehensively documented is that the solution is specific to the specific service you are targeting - there is no generalized solution but rather individual plugins for each service that have their own documentation.

We developed a prototype Azure VM data importer plugin that uses the azure monitor API - mostly as a way to bootstrap people into building the importers they need, and since then community developers have created similar plugins for GCP, Kubernetes, third party data aggregators such as Datadog, etc as well as an improved Azure importer.

You can also use the `mock-observations` plugin to create dummy data for experimenting with. 

I'd be happy to review any PR you raise to dig into this topic on if-docs - thanks!

**Comment by toirl** [comment]
Hey thanks for your quick response. Will provide a proposal in a PR soon. A question for clarification. Using the plugin system ist the preferred way right? Either by writing plugins like the Azure one or using the Shell plugin to integrate external scripts. Im asking as I initially started to generate a manifest file completely independent from the IF which looks like the most easy way to start for me. I am wondering if I should mention this as I do not want to point people in the wrong direction.

**Comment by jmcook1186** [comment]
Yes, we expect people to use plugins to do operations over their input data. To be honest I'm not even sure how you could use IF without plugins unless you are doing inline arithmetic in your yaml file?

**Comment by toirl** [comment]
Hey currently my approach is to have a "template" manifest file which holds basic information and configuration of the components but no data. Based on this file I fetch data for the defined machine. I am using Prometheus here to gather data. The data will then be converted and merged with the template. Well... It is the first approach to get my fingers dirty. But I already learned that there are other better options.
